units:
  temp: c
  pressure: hpa
  speed: kmph
  precip: mm
google_forecast:
  region: curitiba
wunderground_stations:
  - id: ICURIT11
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_direction
      - wind_bearing
      - precip_rate
      - precip_total
  - id: ICURIT21
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_direction
      - wind_bearing
      - precip_total
  - id: ICURIT32
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_direction
      - wind_bearing
      - precip_rate
      - precip_total
  - id: ICURIT41
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_direction 
      - wind_bearing
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: ICURIT44
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_direction
      - wind_bearing
      - precip_rate
      - precip_total
  - id: ICURIT46
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: IPRCURIT2
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
  - id: IPRCURIT8
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: IPRCURIT10
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: ICURITIB15
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total  
  - id: ICURITIB24
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: ICURITIB28
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: ICURITIB29
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: ISOJOS26
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
  - id: ISOJOS29
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation 
  - id: ISOJOS39
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
  - id: ICOLOM18
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation
  - id: IBALSA1
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_total
  - id: IBALSA3
    parameters:
      - temp
      - temp_feel
      - dew_point
      - humidity
      - pressure
      - wind_speed
      - wind_gust
      - wind_bearing
      - wind_direction
      - precip_rate
      - precip_total
      - uv_index
      - radiation