google_forecast:
  region: curitiba
wunderground_stations:
  - id: ICURIT11
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
  - id: ICURIT21
    parameters:
      temp: 0
      dew_point: 4
      humidity: 6
      pressure: 5
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_total: 7
  - id: ICURIT32
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
  - id: ICURIT41
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null
  - id: ICURIT44
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8  
  - id: ICURIT46
    parameters:
      temp: 0
      dew_point: 4
      humidity: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 7
      uv_index: 8
      radiation: null
  - id: IPRCURIT2
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8  
  - id: IPRCURIT8
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null
  - id: IPRCURIT10
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null
  - id: ICURITIB15
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8  
  - id: ICURITIB24
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null
  - id: ICURITIB28
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null
  - id: ICURITIB29
    parameters:
      temp: 0
      dew_point: 4
      humidity: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 7
      uv_index: 8
      radiation: null
  - id: ISOJOS26
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
  - id: ISOJOS29
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null 
  - id: ISOJOS39
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8  
  - id: ICOLOM18
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null
  - id: IBALSA1
    parameters:
      temp: 0
      dew_point: 4
      humidity: 6
      pressure: 5
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_total: 7  
  - id: IBALSA3
    parameters:
      temp: 0
      dew_point: 4
      humidity: 7
      pressure: 6
      wind_speed: 2
      wind_gust: 3
      wind_bearing: null
      precip_rate: 5
      precip_total: 8
      uv_index: 9
      radiation: null